# docker-compose.yml

version: '3.10'
services:
  postgres:
    platform: linux/amd64
    image: postgres:15
    container_name: postgres
    env_file:
      - ./postgres_to_es/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
  elasticsearch:
    image: elasticsearch:8.6.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    container_name:
      elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
     - "9200:9200"

  etl:
    build: postgres_to_es
    env_file:
      - ./postgres_to_es/.env
    container_name:
      postgres_to_es
    depends_on:
      - elasticsearch

volumes:
  es_data:
